### ISSUE TITLE
Keybinds with keypad crashed thinks

### ISSUE THREAD

**Issue by KnatteAnka** [blay09/DefaultKeyConfig#60] opened 2022-02-23 15:39 UTC
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

39.0.79

### Mod Version

defaultoptions-forge-1.18.1-14.1.0.jar

### Describe the Issue

When setting a keybind from keypad in defaultsettings the key stops working.
Example:
changing Default option keybinddings.ext
`key_key.wands.wand_mode:key.keyboard.v:NONE`
To:
`key_key.wands.wand_mode:key.keyboard.keypad.7:NONE`
and that keybind stops working.

### Logs

https://pastebin.com/ncPytk9t

### Do you use any performance-enhancing mods (e.g. OptiFine)?

No only Building wands and default options used + Libs req

**Comment by KnatteAnka** [comment] 2022-02-23 15:40
[keybindings.txt](https://github.com/ModdingForBlockheads/DefaultOptions/files/8125641/keybindings.txt)
Uploading example keybindings file also

**Comment by BlayTheNinth** [comment] 2022-06-13 14:13
Can't reproduce, I defaulted my jump to Numpad 7 and everything worked fine with the exact same key string (`key_key.jump:key.keyboard.keypad.7:NONE`) appearing in the file. 

Is this maybe an issue specific to the Wands mod?

**Comment by KnatteAnka** [comment] 2022-06-13 19:39
Hmm looks like its a compatibility problem with the Wands mod. 

Switched so i set Space to Wand_mode and jump to Keypad 7 and jump still work at keypad7 but not wand_mode

if i delete the row for Wand_mode in keybindings.txt then it starts working again.

Does this help?

Mods used to test first time:
architectury-3.7.22.jar
balm-2.4.3+0.jar
BuildingWands-2.4_beta2_mc1.18.1-forge.jar
cloth-config-6.2.57-forge.jar
defaultoptions-forge-1.18.1-14.1.0.jar

Redid the test after updating newest available mod to below file but still the same problem!
Forge: 39.1.2
architectury-3.9.66
balm-2.4.3+0
BuildingWands-2.5_mc1.18.1-forge
cloth-config-6.2.62-forge
defaultoptions-forge-1.18.1-14.1.0

**Comment by KnatteAnka** [comment] 2022-06-13 19:43
Noted now that even if default is space, Numpad 1 or even O does not work

**Comment by BlayTheNinth** [comment] 2022-06-27 18:23
Closing since the issue lies not within Default Options

**Closed as not planned by BlayTheNinth** 2022-06-27 18:23 UTC
Labels: Caused by Another Mod, Support
